//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPrepared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicaition
    {
        public int reqID { get; set; }
        public string reqName { get; set; }
        public string reqLocation { get; set; }
        public int reqPreviousBalance { get; set; }
        public int reqCurrentBalance { get; set; }
        public int reqCompanyRating { get; set; }
        public System.DateTime reqDate { get; set; }
    }
}
