//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPrepared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class posttable
    {
        public int postID { get; set; }
        public string CName { get; set; }
        public string postTitle { get; set; }
        public string postBody { get; set; }
        public Nullable<System.DateTime> postDate { get; set; }
    }
}
