//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPrepared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transact
    {
        public int TID { get; set; }
        public string InvestorName { get; set; }
        public string StartupName { get; set; }
        public int InvestAmount { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
    }
}
